Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_6_FE, pull requests merged in 2024-03, with the labels that each got.

#8 ✨ Feature - LoadMap, Challenge, Modal(Challenge, Quiz)
  assets/icons/appbar_alarm.svg
  assets/icons/appbar_bookmark.svg
  assets/icons/arrow_back.svg
  assets/icons/arrow_back_black.svg
  assets/icons/arrow_back_blue.svg
  assets/icons/arrow_back_dialog.svg
  assets/icons/arrow_back_white.svg
  assets/icons/clear_challenge.svg
  assets/icons/failed_challenge.svg
  assets/icons/my_image.svg
  assets/icons/server_communication_error.svg
  assets/images/appbar_challenge_logo.svg
  assets/images/appbar_rebook_logo.svg
  assets/images/challenge_start.svg
  assets/images/completed_challenge.svg
  assets/images/connect_1.svg
  assets/images/connect_2.svg
  assets/images/empty.png
  assets/images/empty.svg
  assets/images/incomplete_challenge.svg
  assets/images/matching_character.svg
  assets/images/matching_item_net.svg
  assets/images/matching_succeed.svg
  assets/images/modal_challenge_logo.svg
  assets/images/ongoing_challenge.svg
  assets/images/quiz_1.svg
  assets/images/quiz_1_answer.svg
  assets/images/quiz_2.svg
  assets/images/quiz_2_answer.svg
  ios/Podfile.lock
  lib/app/main_app.dart
  lib/binding/challenge_authentication_binding.dart
  lib/binding/load_map_binding.dart
  lib/binding/login_binding.dart
  lib/binding/matching_binding.dart
  lib/utility/static/app_pages.dart
  lib/utility/static/app_routes.dart
  lib/utility/system/color_system.dart
  lib/view/base/base_screen.dart
  lib/view/challenge_authentication/challenge_authentication_screen.dart
  lib/view/challenge_authentication/fragment/image_input_fragment.dart
  lib/view/challenge_authentication/fragment/loading_fragment.dart
  lib/view/challenge_authentication/fragment/result_fragment.dart
  lib/view/load_map/load_map_screen.dart
  lib/view/load_map/widget/challenge_notice_card.dart
  lib/view/load_map/widget/ongoing_animated_challenge.dart
  lib/view/load_map/widget/round_rectangle_timer_box.dart
  lib/view/login/login_screen.dart
  lib/view/matching/matching_screen.dart
  lib/view/root/root_screen.dart
  lib/view_model/challenge_authentication/challenge_authentication_view_model.dart
  lib/view_model/login/login_view_model.dart
  lib/view_model/matching/matching_view_model.dart
  lib/widget/appbar/default_back_appbar.dart
  lib/widget/dialog/challenge_dialog.dart
  lib/widget/dialog/quiz_dialog.dart
  pubspec.yaml
Labels: feature ✨, 도형

#10 ✨ Feature - Login/User Read API Connection
  ios/Podfile.lock
  lib/app/factory/persistent
  lib/app/factory/secure_storage_factory.dart
  lib/binding/init_binding.dart
  lib/binding/matching_binding.dart
  lib/main.dart
  lib/middleware/login_middleware.dart
  lib/middleware/persistent
  lib/model/root/user_state.dart
  lib/provider/auth/auth_provider.dart
  lib/provider/auth/auth_provider_impl.dart
  lib/provider/base/base_connect.dart
  lib/provider/persistent
  lib/provider/token/token_provider.dart
  lib/provider/token/token_provider_impl.dart
  lib/provider/user/user_remote_provider.dart
  lib/provider/user/user_remote_provider_impl.dart
  lib/repository/auth/auth_repository.dart
  lib/repository/auth/auth_repository_impl.dart
  lib/repository/persistent
  lib/repository/user/user_repository.dart
  lib/repository/user/user_repository_impl.dart
  lib/repository/user_repository.dart
  lib/utility/static/app_pages.dart
  lib/view/login/login_screen.dart
  lib/view_model/login/login_view_model.dart
  lib/view_model/root/root_view_model.dart
  pubspec.yaml
Labels: feature ✨, 형준

#12 ✨ Feature - Home UI
  assets/icons/image_wallpaper.svg
  assets/icons/search.svg
  assets/icons/study_book.svg
  assets/images/quiz_choice_not_right.svg
  assets/images/quiz_choice_right.svg
  assets/images/quiz_result_correct.svg
  assets/images/quiz_result_not_correct.svg
  assets/thumbnail/card_character_green.svg
  assets/thumbnail/profile_character_green.svg
  assets/thumbnail/recycle_can_0.svg
  assets/thumbnail/recycle_can_1.svg
  assets/thumbnail/recycle_clothing_0.svg
  assets/thumbnail/recycle_clothing_1.svg
  assets/thumbnail/recycle_glass_0.svg
  assets/thumbnail/recycle_glass_1.svg
  assets/thumbnail/recycle_paper_0.svg
  assets/thumbnail/recycle_paper_1.svg
  assets/thumbnail/recycle_plastic_0.svg
  assets/thumbnail/recycle_plastic_1.svg
  lib/binding/init_binding.dart
  lib/model/home/card_state.dart
  lib/model/home/quiz_detail_state.dart
  lib/model/home/quiz_state.dart
  lib/model/root/user_state.dart
  lib/model/type/e_recycle.dart
  lib/repository/quiz/quiz_repository.dart
  lib/repository/quiz/quiz_repository_impl.dart
  lib/repository/quiz_history/quiz_history_repository.dart
  lib/repository/quiz_history/quiz_history_repository_impl.dart
  lib/view/home/component/card_container.dart
  lib/view/home/component/horizon_icon_text_button.dart
  lib/view/home/component/vertical_icon_text_button.dart
  lib/view/home/home_screen.dart
  lib/view/home/widget/character_card.dart
  lib/view/home/widget/home_user_view.dart
  lib/view/home/widget/quiz_card.dart
  lib/view/root/root_screen.dart
  lib/view_model/home/home_view_model.dart
  lib/view_model/root/root_view_model.dart
  lib/widget/appbar/default_svg_appbar.dart
  lib/widget/button/rounded_rectangle_text_button.dart
  lib/widget/dialog/quiz_dialog.dart
  pubspec.yaml
Labels: feature ✨, 형준

#15 ✨ Feature - Home UI API Connection
  lib/binding/init_binding.dart
  lib/model/home/quiz_detail_state.dart
  lib/model/home/quiz_history_state.dart
  lib/model/home/quiz_state.dart
  lib/provider/quiz/quiz_remote_provider.dart
  lib/provider/quiz/quiz_remote_provider_impl.dart
  lib/provider/quiz_history/quiz_history_remote_provider.dart
  lib/provider/quiz_history/quiz_history_remote_provider_impl.dart
  lib/repository/quiz/quiz_repository.dart
  lib/repository/quiz/quiz_repository_impl.dart
  lib/repository/quiz_history/quiz_history_repository.dart
  lib/repository/quiz_history/quiz_history_repository_impl.dart
  lib/repository/user/user_repository_impl.dart
  lib/view_model/home/home_view_model.dart
  lib/widget/dialog/quiz_dialog.dart
Labels: feature ✨, 형준

#16 ✨ Feature - Study History, Photo Screen, Widget UI
  lib/widget/seyeon/Photos.dart
  lib/widget/seyeon/RecyclePhotos.dart
  lib/widget/seyeon/bookmark_model.dart
  lib/widget/seyeon/bookmarked.dart
  lib/widget/seyeon/bookmarked_appbar.dart
  lib/widget/seyeon/buildRecycleButtons.dart
  lib/widget/seyeon/contents_popup.dart
  lib/widget/seyeon/my_app.dart
  lib/widget/seyeon/recycle_button.dart
  lib/widget/seyeon/recycle_list.dart
  lib/widget/seyeon/recycle_title.dart
  lib/widget/seyeon/study_appbar.dart
  lib/widget/seyeon/study_bookmark_button.dart
  lib/widget/seyeon/study_picture.dart
Labels: feature ✨, 세영

#18 🎨 Refactor - Study History Screen
  assets/icons/bookmark_empty.svg
  assets/icons/bookmark_fill.svg
  assets/icons/recycle.svg
  ios/Podfile.lock
  lib/binding/init_binding.dart
  lib/binding/study_history_binding.dart
  lib/model/study_history/category_state.dart
  lib/model/study_history/study_history_detail_state.dart
  lib/model/study_history/study_history_state.dart
  lib/provider/study_history/study_history_remote_provider.dart
  lib/provider/study_history/study_history_remote_provider_impl.dart
  lib/repository/study_history/study_history_repository.dart
  lib/repository/study_history/study_history_repository_impl.dart
  lib/utility/static/app_pages.dart
  lib/utility/static/app_routes.dart
  lib/view/home/home_screen.dart
  lib/view/load_map/load_map_screen.dart
  lib/view/study_history/study_history_screen.dart
  lib/view/study_history/widget/category_item.dart
  lib/view/study_history/widget/study_history_item.dart
  lib/view_model/study_history/study_history_view_model.dart
  lib/widget/appbar/default_back_appbar.dart
  lib/widget/button/custom_icon_button.dart
  lib/widget/seyeon/bookmarked.dart
  lib/widget/seyeon/bookmarked_appbar.dart
  lib/widget/seyeon/my_app.dart
  lib/widget/seyeon/recycle_list.dart
  lib/widget/seyeon/study_picture.dart
  pubspec.yaml
Labels: refactor 🎨, 형준

#20 ✨ Feature - Profile, Setting, Withdrawal Screen, Widget UI
  lib/view/profile/withdrawal_screen.dart
  lib/widget/yeonghyeon/color_system.dart
  lib/widget/yeonghyeon/font_system.dart
  lib/widget/yeonghyeon/line.dart
  lib/widget/yeonghyeon/main.dart
  lib/widget/yeonghyeon/pages/profile.dart
  lib/widget/yeonghyeon/pages/setting.dart
  lib/widget/yeonghyeon/pages/withdrawal.dart
  lib/widget/yeonghyeon/rounded_rectangle_text_button.dart
  lib/widget/yeonghyeon/switch.dart
  lib/widget/yeonghyeon/time/custom_time_picker.dart
  lib/widget/yeonghyeon/time/custom_time_picker_dialog.dart
  lib/widget/yeonghyeon/time/section_item.dart
  lib/widget/yeonghyeon/widget/weekly_calendar.dart
Labels: feature ✨, 영현
